MVCVidly/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCVidly.Models;
using System.Data.Entity;
using MVCVidly.ViewModel;

namespace MVCVidly.Controllers
{
    public class MoviesController : Controller
    {
        public ApplicationDbContext _context;

        //create constructor for to allocate instance
        public MoviesController()
        {
            _context = new ApplicationDbContext();
        }

        //create Dispose for dispose the instance
        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }
        // GET: Movies
        public ActionResult Index()
        {
            //var MovieList = _context.Movies.Include(m=>m.Genre).ToList();
            //return View(MovieList);

            if (User.IsInRole(RoleName.CanManageMovies))
                return View("MoviesList");
            return View("ReadOnlyMovies");

        }

        [Authorize(Roles = RoleName.CanManageMovies)]
        public ActionResult CreateMovie()
        {
            var genreList = _context.Genres.ToList();
            MovieFormViewModel newMovieViewModel = new MovieFormViewModel()
            {
                Genres = genreList,
                Movie = new Movie()


            };
            return View("MovieForm", newMovieViewModel);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(Movie movie)
        {
            if (!ModelState.IsValid)
            {
                var genreList = _context.Genres.ToList();
                MovieFormViewModel newMovieViewModel = new MovieFormViewModel()
                {
                    Genres = genreList,
                    Movie = new Movie()


                };
                return View("MovieForm", newMovieViewModel);

            }

            if (movie.Id == 0)
            {
                _context.Movies.Add(movie);
            }
            else
            {
                var movieDetails = _context.Movies.Where(m => m.Id == movie.Id).FirstOrDefault();
                movieDetails.Name = movie.Name;
                movieDetails.GenreId = movie.GenreId;
                movieDetails.DateAdded = movie.DateAdded;
                movieDetails.ReleaseDate = movie.ReleaseDate;
                movieDetails.NumberInStock = movie.NumberInStock;



            }

            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Edit(int id)
        {
            var movieList = _context.Movies.Where(m => m.Id == id).FirstOrDefault();
            MovieFormViewModel movieFormViewModel = new MovieFormViewModel()
            {
                Genres = _context.Genres.ToList(),
                Movie = movieList
            };
            return View("MovieForm", movieFormViewModel);
        }

        public ActionResult Details(int id)
        {
            var movieDetails = _context.Movies.Include(m => m.Genre).Where(m => m.Id == id).FirstOrDefault();
            return View(movieDetails);
        }

        public RedirectToRouteResult Delete(int id)
        {
            var movieDetails = _context.Movies.Where(m => m.Id == id).FirstOrDefault();
            _context.Movies.Remove(movieDetails);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

MVCVidly/Controllers/RentalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCVidly.Controllers
{
    public class RentalController : Controller
    {       
        public ActionResult New()
        {
            return View();
        }
    }
}

MVCVidly/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Vidly", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("New Rental", "New", "Rental")</li>
                    <li>@Html.ActionLink("Customers", "Index", "Customers")</li>
                    <li>@Html.ActionLink("Movie", "Index", "Movies")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @*@Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")*@
    @Scripts.Render("~/bundles/lib")
    @RenderSection("scripts", required: false)
</body>
</html>